AWSTemplateFormatVersion: "2010-09-09"
Description: container on ecs cluster

Resources:
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: "arn:aws:iam::280761544627:role/LabRole"
      ContainerDefinitions:
        - Name: libros
          Image: "280761544627.dkr.ecr.us-east-1.amazonaws.com/libros:latest"
          Cpu: 512
          Memory: 1024
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/api/api-libros"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "api"
          DependsOn:
            - ContainerName: mongodb
              Condition: HEALTHY
          Essential: true
          HealthCheck:
            Command: ["CMD-SHELL", "curl -f http://127.0.0.1:3000/ || exit 1"]
            Interval: 30 # Intervalo entre comprobaciones de salud en segundos
            Timeout: 5 # Tiempo máximo en segundos permitido para una comprobación de salud
            Retries: 3 # Número de veces que se realizará la comprobación antes de declarar el contenedor como no saludable
            StartPeriod: 60 # Tiempo en segundos para esperar antes de comenzar las comprobaciones de salud después del inicio del contenedor
          Environment:
            - Name: MONGO_URL
              Value: "mongodb://127.0.0.1/biblioteca" # Configura la URL de conexión para tu base de datos
            - Name: OAUTH_AUDIENCE
              Value: "https://localhost:3000/api/libros" # Configura la URL de conexión para tu base de datos
            - Name: OAUTH_URL
              Value: "https://dev-lkfqum3zbxve2law.us.auth0.com" # Configura la URL de conexión para tu base de datos
        - Name: mongodb
          Image: "mongo:latest" # Asegúrate de utilizar la imagen de MongoDB adecuada
          Cpu: 512
          Memory: 1024
          PortMappings:
            - ContainerPort: 27017 # Puerto de MongoDB
              Protocol: tcp
          Essential: false
          HealthCheck:
            Command:
              [
                "CMD-SHELL",
                "mongosh --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)'",
              ]
            Interval: 30 # Intervalo entre comprobaciones de salud en segundos
            Timeout: 5 # Tiempo máximo en segundos permitido para una comprobación de salud
            Retries: 3 # Número de veces que se realizará la comprobación antes de declarar el contenedor como no saludable
            StartPeriod: 60 # Tiempo en segundos para esperar antes de comenzar las comprobaciones de salud después del inicio del contenedor
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/db/"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "db"
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: api-libros-service
      TaskDefinition: !Ref Task
      Cluster: !ImportValue "ECSCluster"
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue Subnet1
            - !ImportValue Subnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: libros
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: libros-tg
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
  TaskLogGroupApi:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /api/api-libros # Nombre del log group, se puede personalizar según tu preferencia
      RetentionInDays: 7 # Cantidad de días que se retendrán los registros en el log group. Puedes ajustar esta cantidad según tus necesidades.
  TaskLogGroupMongoDB:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/db/" # Nombre del log group, se puede personalizar según tu preferencia
      RetentionInDays: 7 # Cantidad de días que se retendrán los registros en el log group. Puedes ajustar esta cantidad según tus necesidades.

Outputs:
  ApiEndpoint:
    Description: libros API Endpoint
    Value: !Join ["", ["http://", !ImportValue DomainName]]
    Export:
      Name: "librosApiEndpoint"
